spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fiction?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: qiqi661131hr

server:
  port: 8080
  error:
    path: /error

mybatis:
  mapper-locations: classpath:mapper/*.xml