package com.fiction.mapper;

import com.fiction.entity.Chapter;
import com.fiction.entity.ChapterKey;
import com.fiction.example.ChapterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ChapterMapper {
    long countByExample(ChapterExample example);

    int deleteByExample(ChapterExample example);

    int deleteByPrimaryKey(ChapterKey key);

    int insert(Chapter record);

    int insertSelective(Chapter record);

    List<Chapter> selectByExampleWithRowbounds(ChapterExample example, RowBounds rowBounds);

    List<Chapter> selectByExample(ChapterExample example);

    Chapter selectByPrimaryKey(ChapterKey key);

    int updateByExampleSelective(@Param("record") Chapter record, @Param("example") ChapterExample example);

    int updateByExample(@Param("record") Chapter record, @Param("example") ChapterExample example);

    int updateByPrimaryKeySelective(Chapter record);

    int updateByPrimaryKey(Chapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Chapter selectOneByExample(ChapterExample example);
}