package com.fiction.mapper;

import com.fiction.entity.UserCollectionKey;
import com.fiction.example.UserCollectionExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface UserCollectionMapper {
    long countByExample(UserCollectionExample example);

    int deleteByExample(UserCollectionExample example);

    int deleteByPrimaryKey(UserCollectionKey key);

    int insert(UserCollectionKey record);

    int insertSelective(UserCollectionKey record);

    List<UserCollectionKey> selectByExampleWithRowbounds(UserCollectionExample example, RowBounds rowBounds);

    List<UserCollectionKey> selectByExample(UserCollectionExample example);

    int updateByExampleSelective(@Param("record") UserCollectionKey record, @Param("example") UserCollectionExample example);

    int updateByExample(@Param("record") UserCollectionKey record, @Param("example") UserCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollection
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserCollectionKey selectOneByExample(UserCollectionExample example);
}