package com.fiction.mapper;

import com.fiction.entity.UserFocusKey;
import com.fiction.example.UserFocusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserFocusMapper {
    long countByExample(UserFocusExample example);

    int deleteByExample(UserFocusExample example);

    int deleteByPrimaryKey(UserFocusKey key);

    int insert(UserFocusKey record);

    int insertSelective(UserFocusKey record);

    List<UserFocusKey> selectByExampleWithRowbounds(UserFocusExample example, RowBounds rowBounds);

    List<UserFocusKey> selectByExample(UserFocusExample example);

    int updateByExampleSelective(@Param("record") UserFocusKey record, @Param("example") UserFocusExample example);

    int updateByExample(@Param("record") UserFocusKey record, @Param("example") UserFocusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfocus
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserFocusKey selectOneByExample(UserFocusExample example);
}